### PR TITLE
yoh so i added me as one of the creators

### PR DESCRIPTION
**Pull request by marv1191011910**

### CODE REVIEW

**Comment by JagTheFriend** [comment]
Why ?

**Comment by JagTheFriend** [comment]
Noooo

**Comment by JagTheFriend** [comment]
Make a better of my code

**Comment by JagTheFriend** [comment]
And then create a pr

**Comment by marv1191011910** [comment]
ok

**Comment by JagTheFriend** [comment]
Good luck

**Comment by DeleteUser6969** [comment]
GG

**Pull request closed without merging**
